### ISSUE TITLE
Performance Enhancement: Replace Individual Image Deletion with Docker Prune Method

### ISSUE THREAD

**Issue by UsmanMaan324** [syedmhashim/dockclean#10]
**Issue Context:**
Currently, our image cleanup process involves retrieving a list of all images and then deleting them one by one. This approach can be resource-intensive and time-consuming, especially when there are a significant number of images to manage. To improve our system's performance and efficiency, we propose switching to the `docker.prune` method.

here the docs link for docker.prune method: https://dockerpy.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.prune 
https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.prune

**Rationale for Using `docker.prune`:**
1. **Performance**: The `docker.prune` method is optimized for bulk cleanup, making it significantly faster and less resource-intensive compared to deleting images one by one. This change can lead to substantial performance improvements.

2. **Resource Management**: Efficiently managing Docker resources is crucial for system stability. `docker.prune` automates the removal of not just images but also other unused resources like containers, volumes, and networks, ensuring that our system stays clean and optimized.

3. **Reduced Complexity**: Our current approach involves multiple API calls and error handling for each image deletion. By adopting `docker.prune`, we can simplify our codebase, reduce the likelihood of errors, and improve code maintainability.

**Proposed Action:**
We propose implementing the use of the `docker.prune` method for image cleanup in our system. This change will lead to noticeable performance improvements and more efficient resource management. 

**Cautionary Note:**
Before implementing this change, we should carefully review and document any potential impact on our system. Additionally, we should communicate this change to the team to ensure everyone is aware of the updated image cleanup process.

Let's work together to enhance our system's performance and resource management by adopting the `docker.prune` method for image cleanup.

**Comment by syedmhashim** [comment]
Looks like a good idea. Can we also do the same for containers? @UsmanMaan324

**Comment by UsmanMaan324** [comment]
@SyedMHashim yup we can

**Comment by syedmhashim** [comment]
You're welcome to submit a PR with the proposed changes for images and containers. @UsmanMaan324

**Comment by UsmanMaan324** [comment]
@SyedMHashim PR for this is merged. going to close this issue
