### ISSUE TITLE
Standardize Logging Approach: Replace Print Statements with Logging Library Throughout Codebase

### ISSUE THREAD

**Issue by UsmanMaan324** [syedmhashim/dockclean#6]
### **Issue Context:**
In our current codebase, we have a mix of logging approaches, including using print statements in some places and the logging library in others. This inconsistent logging approach makes it challenging to manage and maintain our code and hinders our ability to effectively monitor and troubleshoot issues.

### Rationale for Standardization:
    1. **Consistency**: Standardizing our logging approach using the logging library throughout the codebase ensures consistency. This uniformity not only improves code readability but also streamlines debugging and maintenance.

    2. **Flexibility**: The logging library offers a range of features like log levels, log formatting, and output destinations (e.g., files, console). This standardization allows us to take advantage of these features, making it easier to adapt our logging strategy as our application evolves.

    3. **Enhanced Debugging**: Debugging is simplified when we have a centralized log repository, as opposed to hunting down print statements scattered throughout the codebase. This change will enable us to trace issues more efficiently and improve our response time to errors.

    4. **Production-Ready**: Using a logging library aligns with best practices for production-ready code. It allows us to configure logging for different environments (development, testing, production) more easily, improving our ability to manage logs in production.

### Proposed Action:
We should replace all print statements with appropriate logging calls using the logging library. This action will bring our code in line with industry standards and significantly improve our codebase's maintainability and robustness.

Let's collaborate on this effort to enhance our logging strategy and ensure smoother development and troubleshooting experiences.

**Comment by syedmhashim** [comment]
Sure. Sounds good to me. I'll take on this one. Thanks for the suggestion.
